ALTER TABLE game
ADD COLUMN league VARCHAR(255),
ADD COLUMN sport VARCHAR(255),
ADD COLUMN country VARCHAR(255),
    ADD FOREIGN KEY (country) REFERENCES country (name_en) ON DELETE CASCADE,
    ADD FOREIGN KEY (sport) REFERENCES sport (name_en) ON DELETE CASCADE,
    ADD FOREIGN KEY (league) REFERENCES league (name_en) ON DELETE CASCADE;