INSERT INTO role (name)
SELECT 'ROLE_MAIN_ADMIN'
    WHERE NOT EXISTS (
    SELECT 1 FROM role WHERE name = 'ROLE_MAIN_ADMIN'
);

INSERT INTO role (name)
SELECT 'ROLE_PLAYER'
    WHERE NOT EXISTS (
    SELECT 1 FROM role WHERE name = 'ROLE_PLAYER'
);

INSERT INTO role (name)
SELECT 'ROLE_LINEMAKER'
    WHERE NOT EXISTS (
    SELECT 1 FROM role WHERE name = 'ROLE_LINEMAKER'
);

INSERT INTO role (name)
SELECT 'ROLE_SUPPORT'
    WHERE NOT EXISTS (
    SELECT 1 FROM role WHERE name = 'ROLE_SUPPORT'
);